import tkinter as tk
import random
import re

# Example variables (you can expand or replace these)
playernumbers = ["Write a tabletop RPG campaign that happens",
"Write a tabletop RPG campaign with 5d5 unique NPC that happens",
]
playersessions = ["in a never-ending series of game sessions",
"over 4d4 sessions",
"in a fast-moving game session",
]
sessionend = ["suspenseful cliffhanger",
"abrupt cliffhanger",
"positive note",
"negative note",
"psychological puzzle",
"mind-twisting puzzle",
]
settingmaster = ["The setting should be {setting}",
"The setting should start out in {setting} and transistion to {setting2}",
"The setting should transistion between the setting of {setting} and {setting2}",
"The setting should transistion back and forth between {setting} and {setting2}",
]
tonemaster = ["The tone should be {tone}",
"The tone should start out in {tone} and transistion to {tone2}",
"The tone should transistion between the tone of {tone} and {tone2}",
"The tone should transistion back and forth between {tone} and {tone2}",
]
settinglist = ["A barren desert with nothing more than dead land for as far as the eye can see",
"A beautiful world filled to the brim with dragons and other amazing creatures, but completely devoid of normal life",
"A boarding school built on an alien planet",
"A castle in the middle of a deep, dark forest",
"A city made entirely out of ice and snow",
"A city of the undead",
"A crowded coffee shop",
"A crowded subway train at rush hour",
"A cruise ship adrift at sea",
"A dark and dangerous world where mutants, robots, cyborgs, zombies, and other vile creatures are constantly trying to kill each other",
"A dark forest full of traps and magical creatures",
"A dark forest full of traps and magical creatures",
"A derelict luxury liner adrift in space (with a secret inside!)",
"A derelict space station floating in orbit around a distant planet",
"A derelict space station floating in orbit around a distant planet",
"A field in springtime",
"A forgotten temple complex nestled in the foothills of a dormant volcano",
"A frozen wasteland",
"A futuristic manufacturing facility",
"A futuristic manufacturing facility with",
"A futuristic mega-city at night, full of glowing billboards advertising products that no one will ever buy (and there's a great deal more to discover!)",
"A futuristic sports arena inside a mountain range",
"A great white wasteland covered entirely in snow and ice. The temperature is far too cold for any sort of human settlement",
"A library at night",
"A lighthouse on an isolated island",
"A lush jungle of tall, sprawling trees that are completely covered in thick vines and tangled undergrowth",
"A massive cave system that has been occupied by orcs for centuries upon centuries",
"A massive cruise ship that has been stranded at sea",
"A massive library full of real, physical books that no one has ever read before",
"A massive tree with a labyrinth of interconnected rooms and underground tunnels deep within its roots, filled with strange creatures like nothing ever seen on Earth before",
"A mysterious technological planet filled with massive construction projects that seem to have no purpose whatsoever",
"A once proud civilization was reduced to ruins by an unknown enemy",
"A peaceful village in the mountains where everything is quiet and calm."
"A peaceful world with lush fields, rolling hills, and deep forests where life is bright and cheery. The sky is always clear blue; there are no storms or hurricanes to be found",
"A post-apocalyptic wasteland",
"A post-apocalyptic wasteland populated by desperate survivors scavenging for resources to survive another day."
"There are still pockets of civilization here and there, but they have fallen into chaos as the population has dwindled due to starvation or plague."
"The landscape is littered with debris from the former days, while the skies are a burning orange and red."
"A quiet coastal town full of quaint little houses sitting at the bottom end of a steep cliffside overlooking calm, glassy waters",
"A quiet little town that has been completely abandoned for reasons still being investigated. It’s everyone for themselves out here in the wasteland, and sometimes people just get sick of living life on their own",
"A rickety old wooden bridge collapsed into the raging river below it",
"A single room in an apartment complex near a major city where strange noises and smells come from beneath the floorboards late at night",
"A small farmhouse on a large plot of farmland, surrounded by woods and swamps on all sides",
"A small shuttlecraft piloted by an AI on its way to explore Pluto",
"A small town that has been cut off from civilization for centuries upon centuries, isolated from humanity behind seemingly impenetrable walls built to keep out dangerous monsters that lurk outside the village’s limits",
"A small, floating island somewhere in the Indian Ocean that is only accessible every seven years when the tides pull it closer to other islands and civilizations ashore",
"A space shuttle orbiting around Jupiter",
"A strange world where everything looks wrong (that’s how it always starts!)",
"A train caught in an avalanche",
"A tropical archipelago filled with exotic wildlife that is home to dangerous sea life",
"A tropical island forgotten by time",
"A wealthy man’s lavish estate sitting alone on top of a hill overlooking the city below it",
"A world filled with genetically modified creatures",
"A world where there are entire civilizations out there that travel to other stars and planets through an inter-dimensional rift or wormhole",
"Abandon Prison Camps from WWI and WWII",
"Abandoned Amusement Parks (Asbury Park, New Jersey)",
"Across the surface of Europa during sunrise over Valhalla Crater",
"Airfields",
"Airports and Airlines",
"Alaskan Wilderness",
"Alien Occupied Earth",
"All Supers World",
"Alternate history",
"Amusement Parks",
"An abandoned amusement park at night",
"An abandoned mansion",
"An abandoned warehouse filled with secret passageways that are impossible to find without help from someone who knows them by heart",
"An aircraft carrier or battleship sitting in the middle of an abandoned port",
"An alien world full of colorful plants/animals (and other creatures) that somehow still manages to be boring as hell. There aren’t many places for settlers to set up shop, so it’s mostly just a large",
"An ancient temple deep within a jungle",
"An empty school after everyone has gone home for the day",
"An endless desert where sandstorms strike without warning and can carry entire structures away if they aren’t built properly to withstand the elements",
"An erupting volcano",
"An industrial complex filled with glowing debris and strange machinery",
"An isolated corner of the cosmos, lit only by distant stars and several smaller moons",
"An isolated prison in the middle of an endless desert",
"An old-west town that has been magically restored to its 19th century glory days (and beyond!)",
"An underground cave system where one can go for days without seeing sunlight or another living being",
"An untamed wilderness filled with wild creatures and beasts of many kinds",
"Ancient Egypt",
"Ancient Underground Cities",
"Any city street, alleyway, or back-alley",
"Any Major Sports Stadium or Arena",
"Any massive stadium or sports arena that has been abandoned by its owners",
"Ape World",
"Arabian Nights",
"Archaic/Biblical",
"Arkship",
"Artificial World",
"Atlantis",
"Atop a large mountain looking down upon a vast desert filled with sand dunes as far as the eye can see",
"Barbarian Europe",
"Beneath the surface of Europa during sunrise over Valhalla Crater",
"Bizarro World",
"Boardwalks with Shops and Stands",
"Boston MA, circa {1d400 + 1630}",
"Brooklyn Academy of Music (BAM) Theatre",
"Camping Out",
"Carnival Cruise Ships",
"Casinos & Gentlemen’s Clubs",
"Castle Dungeon",
"Catacombs",
"Caves",
"Central Park in New York City",
"China Town",
"Châteaus",
"City Under Siege",
"Classical (Greek/Roman/Peloponnesian)",
"Cliffs of Moher (Ireland)",
"Clothing Racks in High-End Department Stores",
"Cloud City",
"Cold War",
"Concert Halls & Opera Houses",
"Construction Sites",
"Contemporary",
"Correctional System",
"Cyberpunk",
"Darkworld",
"Dawn of Civilization",
"Depopulated Earth",
"Desert Planet",
"Disneyland Park",
"Downtown Zoos & Aquariums",
"Dragon",
"Dreamworld",
"Dungeon",
"Dying World",
"Dystopia",
"Early Space Exploration",
"Edwardian Era",
"Elizabethan England",
"English Countryside Manor House",
"Entirely Inside a Computer Program",
"Fallen Civilization",
"Famous Hotel Pools & Resorts",
"Farm",
"Festival",
"First Alien Contact",
"Forest",
"French Revolution",
"Frontier",
"Frozen Wasteland",
"Fruit and Vegetable Market in South Central LA",
"Future Earth",
"Galactic Empires",
"Gas Stations & Convenience Stores",
"Golden Age of Comics",
"Greek Island Resort",
"Grimm's Fairy Tales",
"Hanging Gardens of Babylon",
"Harbor Alley in Hong Kong at Night",
"High-Rise Buildings (NYC, Chicago, etc.)",
"Historic Homes and Buildings",
"Historical",
"Hollywood Theatre",
"In a cave deep beneath a mountain on another world",
"In a dark alley in New York City at night, desperately trying to find your way home from work before something bad happens",
"In a massive city made of towers stacking high into the sky, each one attached to another by bridges and elevators that stretch from floor to floor",
"In a massive library filled to the brim with books so old, they crumble to dust when touched by human hands",
"In a small town in the center of a large valley surrounded by dense forests and thick swamps",
"In a tent at a massive music festival miles away from civilization",
"In the belly of a massive whale as it swims through dark, frigid waters filled with horrific monsters and other life forms from Earth's deepest nightmares",
"In the mouth of a massive dragon as it flies through the sky",
"Industrial Revolution",
"Inside a Presidential Limousine Riding Through Town",
"Inside Amazon forest",
"Inside an Imaginarium (or similar fantasy machine)",
"Inside the body of a giant monster rampaging through the countryside, looking for something to eat",
"Inside the great pyramid of Giza",
"Institution/Institutionalized",
"Interdimensional Space",
"Isolated Space Probe",
"Jungle World",
"Lighthouses",
"Limbo",
"London",
"Lost Civilization",
"Lost/Stranded",
"Mars",
"Mechanized Planet",
"Medieval",
"Microworld",
"Middle Eastern Bazaar",
"Miles of Seawall in Galveston, Texas",
"Military Bases and",
"Military Installation",
"Modern Day Amusement Park",
"Modern Day Las Vegas",
"Modern Day Milwaukee",
"Moon",
"Moto X Track",
"Mount Everest",
"Mount Rushmore",
"Mountain Ranges on Earth",
"Movie Premiere Venues, Awards Shows & Conventions",
"Movie Theatres",
"Museum of Natural History (NYC)",
"Museums, Art Galleries, Libraries & Historical Sites",
"Mystical Orient",
"Near Future",
"Neverland/Childworld",
"Night Clubs & Bars (NYC)",
"Ocean Liner",
"On a far-off planet orbiting a distant star where friendly inhabitants will welcome you with open arms, but be careful about what you accept or take from them",
"On an abandoned oil platform in the middle of an ocean where strange sea creatures lurk, and unknowable horrors hide just out of sight under dark, stormy waters",
"On an elevated platform at the center of a small island",
"On the highway around a major city at rush hour",
"On the set of a cheesy old science fiction movie from the 1960s",
"On the surface of Venus during sunrise over Sif Mons Crater",
"On top of a skyscraper during a thunderstorm at night",
"Orwellian Future",
"Outdoor Skating Rink",
"Outpost",
"Palace and Gardens of Versailles",
"Paris, but it's hell in this instance",
"Parisian Cafe",
"Post-Apocalyptic",
"Pre-European Americas",
"Psychic Near Future",
"Public Parks",
"Rain Forest",
"Realm of the Gods",
"Redwood Forest",
"Remote Future",
"Renaissance",
"Resort/Spa",
"Restaurants with Diners Outside",
"Rio de Janeiro City Streets During Carnival",
"Rural Towns in Any Region of the World",
"Russian State Duma Building (Moscow)",
"School of Magic",
"Sea Adventures",
"Seaside Towns",
"Ships Before They Sink",
"Shopping Malls",
"Ski Slopes",
"Skyscraper",
"Slum Areas in Any Major City Around the World",
"Snowed-in Town",
"Space Colony",
"Space Satellite Control Center (Houston)",
"Space Shuttle LaunchPad",
"Spinning Restaurant",
"Sports Stadiums and Arenas",
"Stadiums and Arenas (Indoor)",
"Steampunk",
"Stone Age",
"Suburban Retail Center",
"Suburbs",
"Subway Station",
"Sword & Sorcery",
"The center of a massive mountain range where nobody has ever ventured",
"The center of the sun",
"The cockpit of an airplane during takeoff or landing in rough weather (I like this one. I’d go for the cockpit of a passenger airliner.)",
"The cold vacuum of space, where nothing lives or grows",
"The deck of a pirate ship sailing the open seas",
"The depths of an ancient jungle filled with giant trees and nocturnal predators whose roars echo through the forest like nothing ever heard before on Earth",
"The edge of space broken by an enormous asteroid field and marked with craters and jagged ridges where stars have fallen to Earth (and beyond!)",
"The first row at a rock concert",
"The Great Pyramids of Giza (Northern Egypt)",
"The Great Wall of China (Northern China)",
"The house at the end of a long, winding road leading to nowhere else but more road with no landmarks or distinguishing characteristics",
"The inside of a department store during the busiest shopping day of the year",
"The inside of a giant amusement park that has been deserted for decades, so anything that can move is inoperable",
"The inside of a giant glass dome where the air is breathable, no one can see in or out, and the inhabitants are completely cut off from the outside world",
"The inside of a massive haunted house or castle",
"The inside of a refrigerator, freezer, walk-in cooler, meat locker, etc",
"The inside of a spaceship or space station has crash-landed on an alien world",
"The Moon",
"The North Pole and the Arctic Ocean",
"The Oval Office of the White House",
"The peak of an active volcano",
"The Planet Mars",
"The seafloor",
"The seafloor",
"The surface of an unknown planet, far away from Earth",
"The surface of Mars during sunrise over Olympus Mons Crater",
"The very tip-top floor of a massive skyscraper",
"The very, very bottom floor of a massive skyscraper that has been abandoned since construction was completed",
"The White House (Washington, DC)",
"Tiny People",
"Tokyo",
"Train Station",
"Traveling Circus",
"Treetop Civilization",
"Tropical Paradise",
"Underground",
"Underground while being chased by trolls with weapons forged from precious metals and stones no human has ever seen before",
"Underwater",
"Underwater - Like 20,000 Leagues Under the Sea",
"Urban Streets of Any Large City",
"Victorian Era",
"Viking Explorers",
"Virtual Reality",
"War",
"War Memorials and Monuments",
"Water Parks and Theme Piers",
"Wild West",
"Wilderness",
"Wildlife Preserve",
"World Government HQ",
"World War [||I|II|III|]",
"Your Place",
]
tonelist = ["Abstract Tech",
"Acid Pixie",
"Acidwave",
"Acubi",
"Adventurecore",
"Adventure Pulp",
"Aetherpunk",
"Afrofuturism",
"Afro-Victorian",
"After Hours",
"Agropeople",
"Ah Beng",
"Alien",
"Alternative",
"Americana",
"American Pioneers",
"American Revolution",
"American Thanksgiving",
"American Tourist Traps",
"Analog Horror",
"Ancient Egypt",
"Androgynous",
"Angelcore",
"Anglocore",
"Anglo Gothic",
"Angura",
"Animecore",
"Anti-Fashion",
"Antique Grunge",
"Arcade",
"Arcadecore",
"Art Academia",
"Art Deco",
"Art Hoe",
"Art Nouveau",
"Arts and Crafts Movement",
"Asian Baby Girl",
"Athlete",
"Atompunk",
"Auroracore",
"Australiana",
"Australian Outback",
"Autumn",
"Autumn Academia",
"Avant Apocalypse",
"Avant-garde",
"Babycore",
"Babygirl",
"Back-to-School",
"Baddie",
"Ballet Academia",
"Balletcore",
"Baltic Violence Tumblr",
"Barbiecore",
"Bardcore",
"Baroque",
"Bastardcore",
"Bauhaus",
"BDSM",
"Beach Bunny",
"Beach Day",
"Beatnik",
"Biker",
"Bimbocore",
"Biopunk",
"Bizarro Fiction",
"Black-Holed Meme",
"Bloomcore",
"Bodikon",
"Bohemian",
"Bombacore",
"Bookstore Girl",
"Bosozoku",
"Boujee",
"Breakcore",
"Britpop",
"Bro",
"Bronzepunk",
"Bubble Bujo",
"Bubble Goth",
"Bubblegum Bitch",
"Bubblegum Witch",
"Cabincore",
"Cagole",
"Camp",
"Campcore",
"Cargopunk",
"Carnivalcore",
"Cartelcore",
"Cartooncore",
"Casino",
"Cassette Futurism",
"Celtic",
"Changelingcore",
"Chaotic Academia",
"Chav",
"Cheiron Crush",
"Cherry Emoji Twitter",
"Chic Modernist",
"Cholo",
"Christcore",
"Christian Girl Autumn",
"Christmas",
"Chunyu",
"City Pop",
"Classic Academia",
"Classicism",
"Classic Lolita",
"Cleancore",
"Clockpunk",
"Clowncore",
"Club",
"Club Kids",
"Coastal Grandmother",
"Coffee House/Cafe",
"Coffinwood",
"Comfy/Cozy",
"Common White Girl",
"Concore",
"Constructivism",
"Corporate",
"Corporate Memphis",
"Corporate Punk",
"Cottagecore",
"Cottagegore",
"Coquette",
"Coquette Academia",
"Country",
"Cozy Childhood Hideaway",
"C-Pop",
"Crackhead",
"Craftcore",
"Cripplepunk",
"Crowcore",
"Crustpunk",
"Cryptid Academia",
"Cryptidcore",
"Cubism",
"Cuddle Party",
"Cultcore",
"Cult Party Kei",
"Cutecore",
"Cyberdelic",
"Cyber Fairy Grunge",
"Cyberghetto",
"Cybergoth",
"Cybergrunge",
"CyberneticPunk",
"Cyberparadism",
"Cyberpop",
"Cyberprep",
"Cyberpunk",
"Cyber Stylin’",
"Danish Pastel",
"Dark Academia",
"Darkcore",
"DarkErrorcore",
"Darkest Academia",
"Dark Fantasy",
"Dark Naturalism",
"Dark Nautical",
"Dark Nymphet",
"Dark Paradise",
"Daydreampunk",
"Dazecore",
"Deathcore",
"Deathrock",
"Decopunk",
"Decora",
"Delicate Sweet",
"Desertwave",
"Desi Romantic Academia",
"De Stijl",
"Dethereal",
"Devilcore",
"Dieselpunk",
"Diner",
"Dionysism",
"Disco",
"Dollar store vernacular",
"Dollette",
"Dolly Kei",
"Doodlecore",
"Downtown Girl",
"Dracopunk",
"Dragoncore",
"Drain",
"Dreamcore",
"Dreamy",
"Drugcore",
"Dual Kawaii",
"Dullcore",
"Dungeon Synth",
"Earthcore",
"E-Boy",
"E-Girl",
"ElectroPop 08",
"Electro Swing",
"Elizabethan England",
"Emo",
"English Major",
"Equestrian",
"Erokawa",
"Eshay",
"Ethereal",
"Europunk",
"Expressionism",
"Fairy Academia",
"Fairycore",
"Fairy Grunge",
"Fairy Kei",
"Fairy Tale",
"Fanfare",
"Fantasy",
"Fantasy Astronomy",
"FantasY2K",
"Farmer's Daughter",
"Fashwave",
"Fauvism",
"Femboy",
"Femcel Weeaboo",
"Femme Fatale",
"Feralcore",
"Film Noir",
"Flapper",
"Flat Design",
"Folk Punk",
"Foodie",
"Forestpunk",
"French Girl",
"French Girly ",
"Frogcore",
"Frutiger Aero",
"Frutiger Eco",
"Frutiger Metro",
"Funky Seasons",
"Furry",
"Futurism",
"Gadgetpunk",
"Game Night",
"Gamercore",
"Gamine",
"Geek",
"Gen X Soft Club",
"Ghostcore",
"Girl-Next-Door",
"Glam Girl",
"Glamorous Los Angeles",
"Glam Rock",
"Glitchcore",
"Gloomcore",
"Glowwave",
"Goblin Academia",
"Goblincore",
"Golden Age of Detective Fiction",
"Golden Hour",
"Gopnik",
"Gorecore",
"Gorpcore",
"Goth",
"Gothcore",
"Gothic",
"Gothic Lolita",
"Grandmillenial",
"Grandparentcore",
"Greaser",
"Green Academia",
"Grifes",
"Grindhouse",
"Groundcore",
"Grunge",
"Gurokawa",
"Gyaru",
"Hackercore",
"Halloween",
"Hallyu",
"Happycore",
"Hatecore",
"Hauntology",
"Haussmann Paris",
"Health Goth",
"Heatwave",
"Heistcore",
"Hellenic",
"Helvetica Aqua Aero",
"Hermaphroditus",
"Hermitpunk",
"Hexatron",
"High School Dream",
"Hikecore",
"Hime Lolita",
"Hi-NRG",
"Hip-Hop",
"Hipness Purgatory",
"Hippie",
"Hipster",
"Historical Americana",
"Holosexual",
"Honeycore",
"Horror",
"Horror Academia",
"Hot Topic",
"Hydrogen",
"Hyperpop",
"Icepunk",
"Imaginarium",
"Impressionism",
"Indicolite",
"Indie",
"Indiecraft",
"Indie Kid",
"Indie Sleaze",
"Internet Academia",
"I-spy",
"Italian Mafia",
"Italian Renaissance",
"Italo Disco",
"Jamcore",
"Jersey Shore",
"Joyride",
"Juggalo",
"Junglecore",
"Jungle Grunge",
"Karasu Zoku",
"Kawaii",
"Kawaii Gamer",
"Key West Kitten",
"Kidcore",
"Kid Science",
"Kimoicore",
"Kinderwhore",
"Kingcore",
"King Gas",
"Kiwiana",
"Knightcore",
"Kogal",
"Korean Cozy Beige",
"Kuromicore",
"Labcore",
"Laborwave",
"Lagenlook",
"Larme Kei",
"La Sape",
"Late 2000s Elementary School",
"Libertywave",
"Light Academia",
"Lightcore",
"Lightningwave",
"Lil Girl",
"Liminal Space",
"Lit Kid",
"Lobotomy-Chic",
"Lo-Fi",
"Lolita",
"Long Island",
"Lounge",
"Lovecore",
"Lunarpunk",
"Macaute",
"Mad Scientist",
"Magewave",
"Magical Girls",
"Maidcore",
"Mallgoth",
"Mall Ninja",
"Maximalism",
"McBling",
"Meatcore",
"Medicalcore",
"Medieval",
"Memphis",
"Mermaid",
"Metal",
"Metalcore",
"Metalheart",
"Metrosexual",
"Miami Metro",
"Midwest Emo",
"Midwest Gothic",
"Military",
"Milk",
"Mind Murder",
"Miniaturecore",
"Minimalism",
"Minivan Rock",
"Miscellaneous Academia",
"Mizuiro",
"Mod",
"Modernism",
"Mori Kei",
"Morute",
"Mosscore",
"Mote Kei",
"MS Paint",
"MTV Green Sky",
"Mulchcore",
"Mushroomcore",
"Musical Academia",
"Mythpunk",
"Nanchatte Seifuku",
"Nanopunk",
"NATOwave",
"Naturecore",
"Nautical",
"Nazi Chic",
"Neko",
"Neoclassicism",
"Neo-Romanism",
"Neo-Tokyo",
"Nerd",
"Nerdcore",
"New Age",
"New England Gothic",
"New Money",
"New Romantic",
"New Wave",
"Newweb",
"Night Luxe",
"Nintencore",
"Normcore",
"Northerness",
"Nostalgiacore",
"Nuclear",
"Nu-Goth",
"Nymphet",
"Ocean Academia",
"Ocean Grunge",
"Old Hollywood",
"Old Memecore",
"Old Money",
"Old Web",
"Onii Kei",
"Oshare Kei",
"Otaku",
"Otherkin",
"Pachuco",
"Pale Grunge",
"Paleocore",
"Palewave",
"Paramilitary",
"Party Animal",
"Party Kei",
"Pastel Academia",
"Pastel Goth",
"Pastel Punk",
"PC Music",
"Peach",
"Pearly",
"Peoplehood",
"Petcore",
"Phony Bureaucracy",
"Photorealism",
"Pink Parisian",
"Pink Pilates Princess",
"Pink Princess",
"Pin-up",
"Pirate",
"Pixel Cutie",
"Pixiecore",
"Plaguecore",
"Plant Mom",
"Playboy",
"Pop Art",
"Pop Kei",
"Post-Apocalyptic",
"Post-Impressionism",
"Post-Punk",
"Post-rock",
"Powwow Step",
"Prairiecore",
"Prehistoricore",
"Preppy",
"Pre-Raphaelite",
"Pretty Preppy",
"Pride flags",
"Princecore",
"Princesscore",
"Printcore",
"Progressive Academia",
"Psychedelica",
"Punk",
"Purism",
"Quality Tumblr",
"Queencore",
"Queer Academia",
"Queercore",
"R&B",
"Racaille",
"Ragecore",
"Rainbowcore",
"Rainy Day",
"Randumb",
"Rangercore",
"Ratcore",
"Ravencore",
"Raver",
"Real Life Super Hero",
"Realism",
"Reefwave",
"Regency",
"Regional Gothic",
"Retro-Futurism",
"Rivethead",
"Roaring 20s",
"Robotics Kids|Robotics Kid",
"Rock",
"Rockabilly",
"Rocketpunk",
"Rococo",
"Roguecore",
"Rollerwave",
"Roma",
"Romantic Academia",
"Romantic Goth",
"Romanticism",
"Romantic Italian",
"Rotcore",
"Royalcore",
"Rusticcore",
"Sadpeople",
"Salon Kei",
"Salvagepunk",
"Sandalpunk",
"Sanriocore",
"Scene",
"Schizowave",
"Science Academia",
"Scoutcore",
"Scrapbook",
"Scrapper",
"Seapunk",
"Selkiecore",
"Shabby Chic",
"Shamate",
"Shanzhai",
"Sharpies",
"Shibuya Punk",
"Shironuri",
"Shoegaze",
"Sigilkore",
"Sigma Male",
"Sizz",
"Skater ",
"Skeuomorphism",
"Skinheads",
"Slimepunk",
"Sloanie",
"Slutcore",
"Smilecore",
"Snow Bunny",
"Snowdrop",
"Soft Apocalypse",
"Soft Grunge",
"Softie",
"Soft indie",
"Soft Macabre",
"Soggy",
"Solarpunk",
"Southern Belle",
"Southern Gothic",
"Sovietwave",
"Spacecore",
"Space Cowboy",
"Sparklecore",
"Spiritcore",
"Spring",
"Spy Fiction",
"Starrflesh",
"Steampunk",
"Steelpunk",
"Stilyagi",
"Stimwave",
"Stonepunk",
"Stoner",
"Stripcore",
"Studyblr",
"Studyplace",
"Suburban Gothic",
"Sukeban",
"Summer",
"Superflat Pop",
"Suprematism",
"Surf Crush",
"Surrealism",
"Surreal Memer",
"Swenkas",
"Swordpunk",
"Synthwave",
"Tacticool",
"Taisho Roman",
"Takenokozoku",
"Tanbi Kei",
"TangoCore",
"Technical Scene",
"Technocore",
"Technozen",
"Techwear",
"Teddies",
"Teenage Dream",
"Teenqueen",
"Teethcore",
"Terrorwave",
"Teslapunk",
"That Girl",
"Theatre Academia",
"Theatre Kids",
"Thrasher",
"Thriftcore",
"Tiki",
"Tinkercore",
"Tinycore",
"Tomboy",
"Toxic Core",
"Trad Goth",
"Traditional Korean",
"Trailer Park Princess",
"Trashcore",
"Trashy Raver",
"Traumacore",
"Trenchcore",
"Trendercore",
"Trillwave",
"Tropical",
"Tumblewave",
"Tupinipunk",
"Twee",
"Tweencore",
"Ukiyo-e",
"Unicorncore",
"Urban Fantasy",
"Urbancore",
"Utopian Scholastic",
"Vacation Dadcore",
"Vampire",
"Vaporwave",
"VARIOUSXYZ",
"Vectorbloom",
"Vectorheart",
"Vibrant Academia",
"Victorian",
"Victorian Goth",
"Victorian Urban Poverty",
"Viking",
"Villagecore",
"Villaincore",
"Vintage British Sportsman",
"Vintage Parisian",
"Virgo's Tears",
"Visual Kei",
"Voidcore",
"Voidpunk",
"Vorticism",
"VSCO",
"VSCO Preppy",
"Vulture Culture",
"Wabi-Sabi",
"Waif",
"Waldorf",
"Wanderlust",
"Warmcore",
"Weathercore",
"Web Creep",
"Weeaboo",
"Weirdcore",
"Werewolf",
"Western",
"Wetcore",
"Whimsigothic",
"Wild Child",
"Winter",
"Winter Fairy Coquette",
"Witchcore",
"Witch House",
"Witchy Academia",
"Wizardcore",
"Wonderland",
"Woodland goth",
"Wormcore",
"Writer Academia",
"Wuxia",
"Y2K",
"Yakuza",
"Yami Kawaii",
"Yandere",
"Yankeecore",
"Yanki",
"Youthquake",
"Yume Kawaii",
"Zombiecore"
]

firstthings = ["Advanced Intelligence",
"Afterlife",
"Alien",
"Alliance",
"Alternate History",
"Animal",
"Anthropomorphic Objects",
"Artificial Intelligence",
"Atomic Monster",
"Big Business",
"Blood",
"Bogeyman",
"Castle",
"Church",
"Computers",
"Conspiracy",
"Correctional System",
"Dam",
"Demon",
"Deity",
"Disaster",
"Disease",
"Dragons",
"Dungeon",
"Elves",
"Empire",
"Epic Heroes",
"Espionage",
"Exploration",
"Fairy",
"Fire",
"Frontier",
"Furry",
"Gang Warfare",
"Garbage",
"Genetic Engineering",
"Ghost Town",
"Giant",
"Heaven & Hell",
"High Magic",
"Hotel",
"Immortals",
"Insanity",
"Invaders/Outsiders",
"Limbo",
"Lost Tribe",
"Low Magic",
"Mass Transit",
"Mecha",
"Military",
"Monkeys",
"Movie Monsters",
"Music",
"Mutants/Mutations",
"Mysterious Energy",
"Nanotech",
"Neutral Ground",
"Neutrality",
"Ninjas",
"Occult",
"Organized Crime",
"Pirate",
"Political Intrigue",
"Pollution",
"Powers",
"Prophesy",
"Psychic Ability",
"Realm of the Gods",
"Robots/Automatons",
"Royal Bloodline",
"Ruins",
"Sci-Fi",
"Secret Society",
"Serial Killer",
"Ship",
"Space",
"Special Ops",
"Spy",
"Steampunk",
"Street Gangs",
"Stronghold",
"Suburb",
"Supernatural",
"Supers",
"Territory",
"Terrorist",
"Time Travel",
"Trade",
"Troubled Youth",
"Ultimate Weapon",
"Undead",
"Underground Pariahs",
"Unusual Phenomena",
"Vampire",
"Virtual Reality",
"War",
"Water",
"Werewolf",
"Wild Animals",
"Wilderness",
"World Domination",
"Armory",
"Artifact",
"Auditorium",
"Blackmail",
"Brains",
"Bugs",
"Burrow",
"Business Office",
"Cannonfodder",
"Child",
"Confinement",
"Cover Up",
"Crash Site",
"Disguise",
"Docks",
"Door",
"Dreams",
"Duel",
"Elected Official",
"Election",
"Elvis",
"Faith",
"Farm",
"Festival",
"Fight",
"Gambling",
"Government Agents",
"Government Office",
"Grave",
"Grudge",
"Guard",
"Guide",
"Heir",
"Heist",
"Hired Muscle",
"Honor",
"Horseman",
"Hostage",
"Hunt",
"Illness",
"Intrigue",
"Invention",
"Island",
"Janitor",
"Kingpin",
"Lair",
"Launch",
"Law Enforcement",
"Lawyer",
"Leader",
"Marketplace",
"Martial Arts",
"Mask",
"Mechanic",
"Mercenaries",
"Mindless Horde",
"Mob",
"Murder",
"Mystery",
"Natural Disaster",
"Newborn",
"Nightclub/Rave",
"Noble",
"Note",
"Park",
"People",
"Poison",
"Political Group",
"Prayer",
"Prisoner",
"Prostitute",
"Rebels",
"Red Herring",
"Religious Fanatics",
"Research",
"Restaurant",
"Revenge",
"Road",
"Romance",
"School",
"Secret",
"Security Forces",
"Sleep",
"Soldier",
"Sporting Event",
"Store",
"Student",
"Survival",
"Tavern",
"Teacher",
"Theatre",
"Town Square",
"Traitor",
"Travel",
"Treasure",
"Treaty",
"Untimely Death",
"Vehicle",
"Warehouse",
"Wedding",
]
thingstoinclude = ["Use the THINGS to give some suggestions of the plot, using ACTIONS to drive the plot.",
"Use the THINGS to develop the game around the players, and give suggestions how the players can use ACTIONS to complete tasks that show up in the game.",
]
firstactions = ["Alert",
"Assassinate",
"Blackmail",
"Brainwash",
"Build",
"Celebrate",
"Clean",
"Clear",
"Collect",
"Convince",
"Cover Up",
"Defend",
"Deliver",
"Destroy",
"Discover",
"Disguise",
"Duel",
"Escape",
"Explore",
"Fight",
"Fire",
"Guard",
"Guide",
"Hide",
"Humiliate",
"Hunt",
"Infiltrate",
"Intimidate",
"Kidnap",
"Launch",
"Liberate",
"Lose",
"Mimic",
"Murder",
"Negotiate",
"Poison",
"Purchase",
"Recover",
"Reject",
"Rescue",
"Research",
"Scare",
"Seduce",
"Spy",
"Steal",
"Survive",
"Teach",
"Trade",
"Travel",
"Win",
]
writingmethod = ["a bulleted outline describing the world the players will be playing in. 1st level bullets describe major locations (cities, metropolis, significant areas); 2nd level describes minor locations or NPC's that exist inside those 1st level locations; 3rd level can build off 2nd level, and so on.",
"a bulleted outline of the story. 1st level should be the major plot points; 2nd level should be minor plot points; 3rd level should be ideas for character arcs; 4th level should be possible events.",
"suggestions on how the campaign starts and slowly progress the story, giving suggestions about the plot, player development, and NPC arcs.",
"suggestions how to develop the world so I can allow the players freedom to do whatever they like.",
]

# Dice roll parser
def roll_dice(expr):
    match = re.fullmatch(r"(\d*)d(\d+)([+-]\d+)?", expr)
    if not match:
        return expr  # Not a valid dice expression, return as-is
    
    num, die, modifier = match.groups()
    num = int(num) if num else 1
    die = int(die)
    modifier = int(modifier) if modifier else 0
    
    total = sum(random.randint(1, die) for _ in range(num)) + modifier
    return str(total)

# Replace all dice expressions in a string with their result
def process_dice_rolls(text):
    return re.sub(r"(\d*d\d+([+-]\d+)?)", lambda m: roll_dice(m.group(1)), text)

# Generate the RPG prompt
def generate_prompt():
    playernum = random.choice(playernumbers)
    playerses = random.choice(playersessions)
    sesend = random.choice(sessionend)
    setting = random.choice(settinglist)
    setting2 = random.choice(settinglist)
    tone = random.choice(tonelist)
    tone2 = random.choice(tonelist)
    writethis = random.choice(writingmethod)
    include = random.choice(thingstoinclude)
    things_list = random.sample(firstthings, 5)
    things = ", ".join(things_list)
    actions_list = random.sample(firstactions, 5)
    actions = ", ".join(actions_list)
    
    # Choose and format setting prompt after setting/setting2 are known
    setting_template = random.choice(settingmaster)
    setmast = setting_template.format(setting=setting, setting2=setting2)
    tone_template = random.choice(tonemaster)
    tonemast = tone_template.format(tone=tone, tone2=tone2)

    prompt_template = (
    "{playernum} {playerses}. Every session before the final session should end on a {sesend}.\n\n"
    "{setmast}\n\n{tonemast}.\n\nWrite the first scene of how the campaign starts, giving me {writethis}\n\nOnly write one scene. I will request the next scene after telling you how the game went.\n\n"
    "{include}\n\nTHINGS: {things}\n\nACTIONS: {actions}"
)

    # Final formatting
    filled_prompt = prompt_template.format(
    playernum=playernum,
    playerses=playerses,
    sesend=sesend,
    setmast=setmast,
    tonemast=tonemast,
    writethis=writethis,
    include=include,
    things=things,
    actions=actions,
)

    # Replace dice rolls if present
    final_prompt = process_dice_rolls(filled_prompt)

    print(final_prompt)
    text_output.delete("1.0", tk.END)
    text_output.insert(tk.END, final_prompt)

def copy_to_clipboard():
    text = text_output.get("1.0", tk.END).strip()
    root.clipboard_clear()
    root.clipboard_append(text)
    root.update()  # Keeps clipboard contents after app is closed

# GUI setup
root = tk.Tk()
root.title("AI Prompt Generator")

# Create a frame to hold both buttons in a single row
button_frame = tk.Frame(root)
button_frame.pack(pady=10)

generate_button = tk.Button(button_frame, text="Generate Prompt", command=generate_prompt)
generate_button.pack(side=tk.LEFT, padx=5)

copy_button = tk.Button(button_frame, text="Copy to Clipboard", command=copy_to_clipboard)
copy_button.pack(side=tk.LEFT, padx=5)

text_output = tk.Text(root, height=25, width=70, wrap=tk.WORD)
text_output.pack(padx=10, pady=10)

root.mainloop()
